local _, CF = ...
CF:RegisterModule("Panels", { Deferred = "Generic panels, curved portrait replacements and party/raid/boss skins remain native pending client checks; named window modules are separate" })
